routes/admin.php
<?php
    Route::group(['prefix' => 'manage','namespace'=>'App\\Http\\'. $controller .'\\','as' =>'admin.','middleware'=>['web','auth']], function () {
        Route::get('/', function(){
            return redirect()->route('admin.users.index');
        });
        Route::resource('/users','UserController');
        Route::resource('/roles','RoleController');
        Route::resource('/permissions','PermissionController');
    });

?>

routes/front.php
<?php
    Route::group(['prefix' => '','namespace'=>'App\\Http\\'. $controller .'\\','as' =>'front.','middleware'=>['web']], function () {
        Route::view('/','layouts.front_layout');
    });

?>

routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
$controller = 'Controllers\\Admin';
$livewire = 'Livewire\\Admin';

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

include_once('front.php');
include_once('admin.php');

resources/views/layouts/partials/admin/ace_head.blade.php
<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <base href="/" />

    <title>@yield('pagetitle','Admin Dashboard Layout')</title>

    <!-- include common vendor stylesheets & fontawesome -->
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/@fortawesome/fontawesome-free/css/fontawesome.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/@fortawesome/fontawesome-free/css/regular.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/@fortawesome/fontawesome-free/css/brands.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/@fortawesome/fontawesome-free/css/solid.css">
    <!-- include fonts -->
    {{-- <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/dist/css/ace-font.css"> --}}
    <!-- ace.css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/node_modules/select2/dist/css/select2.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('public/backend') }}/dist/css/ace.css">
    <!-- favicon -->
    <link rel="icon" type="image/png" href="{{ asset('public/backend') }}/favicon.png" />
    <style>
        body{
            font-family: 'Hanuman', 'serif' !important;
        }
    </style>
    @stack('styles')
    {{-- @livewireStyles --}}
  </head>

resources/views/layouts/partials/admin/footer.blade.php
<footer class="footer d-none d-sm-block footer-fixed">
    <div class="footer-inner bgc-white-tp1">
      <div class="pt-3 border-none border-t-3 brc-grey-l2 border-double">
        <span class="text-primary-m1 font-bolder text-120">Ace</span>
        <span class="text-grey">Application &copy; 2021</span>

        <span class="mx-3 action-buttons">
              <a href="#" class="text-blue-m2 text-150"><i class="fab fa-twitter-square"></i></a>
              <a href="#" class="text-blue-d2 text-150"><i class="fab fa-facebook"></i></a>
              <a href="#" class="text-orange-d1 text-150"><i class="fa fa-rss-square"></i></a>
          </span>
      </div>
    </div><!-- .footer-inner -->

    <!-- `scroll to top` button inside footer (for example when in boxed layout) -->
    <div class="footer-tools">
      <a href="#" class="btn-scroll-up btn btn-dark mb-2 mr-2">
        <i class="fa fa-angle-double-up mx-2px text-95"></i>
      </a>
    </div>
  </footer>
  <!-- footer toolbox for mobile view -->
  <footer class="d-sm-none footer footer-sm footer-fixed">
    <div class="footer-inner">
      <div class="btn-group d-flex h-100 mx-2 border-x-1 border-t-2 brc-primary-m3 bgc-white-tp1 radius-t-1 shadow">
        <button class="btn btn-outline-primary btn-h-lighter-primary btn-a-lighter-primary border-0" data-toggle="modal" data-target="#id-ace-settings-modal">
          <i class="fas fa-sliders-h text-blue-m1 text-120"></i>
        </button>

        <button class="btn btn-outline-primary btn-h-lighter-primary btn-a-lighter-primary border-0">
          <i class="fa fa-plus-circle text-green-m1 text-120"></i>
        </button>

        <button class="btn btn-outline-primary btn-h-lighter-primary btn-a-lighter-primary border-0" data-toggle="collapse" data-target="#navbarSearch" aria-controls="navbarSearch" aria-expanded="false" aria-label="Toggle navbar search">
          <i class="fa fa-search text-orange text-120"></i>
        </button>

        <button class="btn btn-outline-primary btn-h-lighter-primary btn-a-lighter-primary border-0 mr-0">
          <span class="pos-rel">
              <i class="fa fa-bell text-purple-m1 text-120"></i>
              <span class="badge badge-dot bgc-red position-tr mt-n1 mr-n2px"></span>
          </span>
        </button>
      </div>
    </div>
  </footer>

resources/views/layouts/partials/admin/left_sidebar.blade.php
<div id="sidebar" class="sidebar sidebar-fixed expandable sidebar-light">
    <div class="sidebar-inner">

      <div class="ace-scroll flex-grow-1" data-ace-scroll="{}">
        <ul class="nav has-active-border active-on-right">
          <li class="nav-item active">
            <a href="{{ Route('home') }}" class="nav-link">
              <i class="nav-icon fa fa-tachometer-alt"></i>
              <span class="nav-text fadeable">
                <span>{{ trans('menus.dashboard') }}</span>
              </span>
            </a>
            <b class="sub-arrow"></b>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link dropdown-toggle collapsed">
              <i class="nav-icon fa fa-table"></i>
              <span class="nav-text fadeable">
                     <span>{{ trans('menus.user.management') }}</span>
              </span>
              <b class="caret fa fa-angle-left rt-n90"></b>
            </a>
            <div class="hideable submenu collapse">
              <ul class="submenu-inner">
                <li class="nav-item">
                  <a href="{{ route('admin.roles.index') }}" class="nav-link">
                    <span class="nav-text">
                        <span>{{ trans('menus.role') }}</span>
                    </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('admin.permissions.index') }}" class="nav-link">
                    <span class="nav-text">
                        <span>{{ trans('menus.permission') }}</span>
                    </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{{ route('admin.users.index') }}" class="nav-link">
                    <span class="nav-text">
                        <span>{{ trans('menus.user') }}</span>
                    </span>
                  </a>
                </li>
              </ul>
            </div>
            <b class="sub-arrow"></b>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link dropdown-toggle collapsed">
              <i class="nav-icon fa fa-edit"></i>
              <span class="nav-text fadeable">
               <span>Forms</span>
              </span>
              <b class="caret fa fa-angle-left rt-n90"></b>
            </a>
            <div class="hideable submenu collapse">
              <ul class="submenu-inner">
                <li class="nav-item">
                  <a href="html/form-basic.html" class="nav-link">
                    <span class="nav-text">
                           <span>Basic Elements</span>
                    </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="html/form-more.html" class="nav-link">
                    <span class="nav-text">
                           <span>More Elements</span>
                    </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="html/form-wizard.html" class="nav-link">
                    <span class="nav-text">
                           <span>Wizard &amp; Validation</span>
                    </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="html/form-upload.html" class="nav-link">
                    <span class="nav-text">
                           <span>File Upload</span>
                    </span>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="html/form-wysiwyg.html" class="nav-link">
                    <span class="nav-text">
                        <span>Wysiwyg &amp; Markdown</span>
                    </span>
                  </a>
                </li>
              </ul>
            </div>
            <b class="sub-arrow"></b>
          </li>
        </ul>
      </div><!-- /.sidebar scroll -->

      <div class="sidebar-section">
        <div class="sidebar-section-item fadeable-bottom">
          <div class="fadeinable">
            <!-- shows this when collapsed -->
            <div class="pos-rel">
              <img alt="Alexa's Photo" src="{{ asset('public/backend') }}/assets/image/avatar/avatar3.jpg" width="42" class="px-1px radius-round mx-2 border-2 brc-default-m2" />
              <span class="bgc-success radius-round border-2 brc-white p-1 position-tr mr-1 mt-2px"></span>
            </div>
          </div>
          <div class="fadeable hideable w-100 bg-transparent shadow-none border-0">
            <!-- shows this when full-width -->
            <div id="sidebar-footer-bg" class="d-flex align-items-center bgc-white shadow-sm mx-2 mt-2px py-2 radius-t-1 border-x-1 border-t-2 brc-primary-m3">
              <div class="d-flex mr-auto py-1">
                <div class="pos-rel">
                  <img alt="Alexa's Photo" src="{{ asset('public/backend') }}/assets/image/avatar/avatar3.jpg" width="42" class="px-1px radius-round mx-2 border-2 brc-default-m2" />
                  <span class="bgc-success radius-round border-2 brc-white p-1 position-tr mr-1 mt-2px"></span>
                </div>

                <div>
                  <span class="text-blue-d1 font-bolder">Alexa</span>
                  <div class="text-80 text-grey">
                    Admin
                  </div>
                </div>
              </div>
              <a href="#" class="d-style btn btn-outline-primary btn-h-light-primary btn-a-light-primary border-0 p-2 mr-2px ml-4" title="Settings" data-toggle="modal" data-target="#id-ace-settings-modal">
                <i class="fa fa-cog text-150 text-blue-d2 f-n-hover"></i>
              </a>
              <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
              class="d-style btn btn-outline-orange btn-h-light-orange btn-a-light-orange border-0 p-2 mr-1" title="Logout">
                <i class="fa fa-sign-out-alt text-150 text-orange-d2 f-n-hover"></i>
              </a>
                 <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
                </form>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

resources/views/layouts/partials/admin/script.blade.php
<script src="{{ asset('public/backend') }}/node_modules/jquery/dist/jquery.js"></script>
<script src="{{ asset('public/backend') }}/node_modules/popper.js/dist/umd/popper.js"></script>
<script src="{{ asset('public/backend') }}/node_modules/bootstrap/dist/js/bootstrap.js"></script>
@include('sweetalert::alert')
<script src="{{ asset('public/backend') }}/node_modules/select2/dist/js/select2.js"></script>
@stack('scripts')
<script src="{{ asset('public/backend') }}/dist/js/ace.js"></script>